// Sample story data — cyberpunk hacker thriller
// Bilingual (PT-BR / EN). Nodes laid out for the graph canvas.

const STORY = {
  pt: {
    title: "Sinal_Fantasma",
    author: "K. Ribeiro",
    sceneTitle: "intro_grid",
    sceneSubtitle: "Cena 1 de 7 · 2.847 palavras",
    scenes: [
      { id: "startup", name: "startup", words: 412, nodes: 6, isStart: true },
      { id: "intro_grid", name: "intro_grid", words: 2847, nodes: 18, current: true },
      { id: "midnight_market", name: "midnight_market", words: 3104, nodes: 24 },
      { id: "ice_breaker", name: "ice_breaker", words: 1980, nodes: 14 },
      { id: "the_burn", name: "the_burn", words: 4221, nodes: 31, warning: true },
      { id: "rooftop", name: "rooftop", words: 1644, nodes: 11 },
      { id: "endings", name: "endings", words: 892, nodes: 8 },
      { id: "stats", name: "choicescript_stats", words: 220, nodes: 3, special: true },
    ],
    variables: [
      { name: "nome_runner", type: "string", initial: '""', desc: "Nome do(a) protagonista", uses: 47 },
      { name: "nervos", type: "number", initial: "50", desc: "Sangue-frio sob pressão (0–100)", uses: 23, fairmath: true },
      { name: "codigo", type: "number", initial: "30", desc: "Habilidade técnica", uses: 31, fairmath: true },
      { name: "rua", type: "number", initial: "40", desc: "Instinto de rua", uses: 19, fairmath: true },
      { name: "creditos", type: "number", initial: "1200", desc: "Saldo na carteira fria", uses: 28 },
      { name: "tem_deck", type: "boolean", initial: "true", desc: "Possui o cyberdeck antigo do Tio Sá", uses: 12 },
      { name: "lealdade_kana", type: "number", initial: "0", desc: "Confiança da Kana (-100 a 100)", uses: 16 },
      { name: "viu_corpo", type: "boolean", initial: "false", desc: "Encontrou o corpo no beco", uses: 8 },
    ],
    achievements: [
      { id: "primeiro_hack", title: "Primeiro Hack", points: 5, desc: "Quebrou o ICE de uma loja barata.", hidden: false },
      { id: "ghost_protocol", title: "Protocolo Fantasma", points: 25, desc: "Terminou a cena sem deixar rastro digital.", hidden: false },
      { id: "lobo_solitario", title: "Lobo Solitário", points: 40, desc: "Recusou todas as ofertas de ajuda.", hidden: true },
      { id: "kana_apaixonada", title: "Sob a Chuva de Néon", points: 15, desc: "Romance com Kana desbloqueado.", hidden: true },
    ],
    nodes: [
      {
        id: "n1", type: "passage", x: 60, y: 60, w: 320,
        title: "abertura",
        body: "A chuva ácida cai há três dias. Você está no telhado do prédio 7 do Setor Tókio-Sul, com o velho cyberdeck do Tio Sá pesando na mochila. Lá embaixo, néon de holo-anúncios rastejando nas poças.",
        sets: [{ var: "nervos", op: "=", val: "50" }],
      },
      {
        id: "n2", type: "set", x: 430, y: 60, w: 240,
        title: "*set inicial",
        sets: [
          { var: "nervos", op: "=", val: "50" },
          { var: "codigo", op: "=", val: "30" },
          { var: "rua", op: "=", val: "40" },
        ],
      },
      {
        id: "n3", type: "choice", x: 60, y: 320, w: 360,
        title: "primeira_decisão",
        prompt: "O que você faz?",
        options: [
          { text: "Descer pela escada de incêndio.", to: "n5", cond: null },
          { text: "Pular para o telhado vizinho.", to: "n6", cond: { type: "if", expr: "nervos >= 40" } },
          { text: "Conectar o deck na antena agora.", to: "n7", cond: { type: "selectable_if", expr: "tem_deck" } },
          { text: "Esperar a patrulha passar.", to: "n8", cond: null, hideReuse: true },
        ],
      },
      {
        id: "n4", type: "if", x: 720, y: 60, w: 280,
        title: "*if tem_deck",
        branches: [
          { kind: "if", expr: "tem_deck and codigo > 25", to: "n9" },
          { kind: "elseif", expr: "tem_deck", to: "n10" },
          { kind: "else", to: "n11" },
        ],
      },
      {
        id: "n5", type: "passage", x: 60, y: 620, w: 300,
        title: "escada_incendio",
        body: "Os degraus de metal gemem sob seu peso. No terceiro andar, você ouve vozes — guardas corporativos, sotaque do Norte. ${nome_runner}, você prende a respiração.",
        sets: [{ var: "nervos", op: "%-", val: "10" }],
      },
      {
        id: "n6", type: "passage", x: 430, y: 360, w: 300,
        title: "salto",
        body: "Cinco metros de vazio entre os prédios. Você corre. O ar cheira a ozônio. @{nervos alto|médio|baixo} o salto sai @{nervos limpo|tremido|catastrófico}.",
        sets: [
          { var: "nervos", op: "%+", val: "5" },
          { var: "rua", op: "%+", val: "8" },
        ],
      },
      {
        id: "n7", type: "passage", x: 770, y: 360, w: 300,
        title: "antena_quente",
        body: "O deck do Tio Sá esquenta nas suas mãos. A interface neural pisca em ámbar — você está dentro da grade municipal. Quase fácil demais.",
        sets: [{ var: "codigo", op: "%+", val: "12" }],
      },
      {
        id: "n8", type: "label", x: 60, y: 880, w: 200,
        title: "*label esperar",
      },
      {
        id: "n9", type: "goto_scene", x: 1060, y: 60, w: 240,
        title: "*goto_scene midnight_market",
        target: "midnight_market",
      },
      {
        id: "n10", type: "gosub", x: 1060, y: 200, w: 240,
        title: "*gosub verificar_deck",
      },
      {
        id: "n11", type: "ending", x: 1060, y: 340, w: 240,
        title: "*ending — 'sem deck'",
      },
      {
        id: "n12", type: "checkpoint", x: 430, y: 880, w: 240,
        title: "*save_checkpoint pre_market",
      },
      {
        id: "n13", type: "choice", x: 770, y: 660, w: 340,
        title: "encontro_kana",
        prompt: "Kana levanta o capuz. Olhos de ferro.",
        options: [
          { text: "“Você está atrasada.”", to: "n14", cond: null },
          { text: "“Senti sua falta.”", to: "n14", cond: { type: "if", expr: "lealdade_kana > 20" } },
          { text: "Sacar a arma.", to: "n15", cond: { type: "selectable_if", expr: "rua > 50" } },
        ],
      },
      {
        id: "n14", type: "passage", x: 1170, y: 580, w: 300,
        title: "kana_responde",
        body: "Ela sorri torto. — Cala a boca, ${nome_runner}. Vamos.",
        sets: [{ var: "lealdade_kana", op: "+", val: "5" }],
      },
      {
        id: "n15", type: "passage", x: 1170, y: 760, w: 300,
        title: "tensao",
        body: "A pistola pesa. Kana não pisca.",
        warning: "loop potencial: nó retorna a *label esperar sem alterar estado",
      },
    ],
    edges: [
      { from: "n1", to: "n2", kind: "flow" },
      { from: "n2", to: "n4", kind: "flow" },
      { from: "n1", to: "n3", kind: "flow" },
      { from: "n3", to: "n5", kind: "choice", label: "#1" },
      { from: "n3", to: "n6", kind: "choice", label: "#2 *if" },
      { from: "n3", to: "n7", kind: "choice", label: "#3 *selectable_if" },
      { from: "n3", to: "n8", kind: "choice", label: "#4" },
      { from: "n4", to: "n9", kind: "if" },
      { from: "n4", to: "n10", kind: "elseif" },
      { from: "n4", to: "n11", kind: "else" },
      { from: "n6", to: "n12", kind: "flow" },
      { from: "n7", to: "n12", kind: "flow" },
      { from: "n12", to: "n13", kind: "flow" },
      { from: "n13", to: "n14", kind: "choice", label: "#1" },
      { from: "n13", to: "n14", kind: "choice", label: "#2 *if" },
      { from: "n13", to: "n15", kind: "choice", label: "#3 *selectable_if" },
      { from: "n15", to: "n8", kind: "goto", label: "*goto esperar" },
    ],
    lints: [
      { level: "error", msg: "label “esperar_demais” referenciado mas não existe", scene: "intro_grid", node: "n8", line: 142 },
      { level: "warning", msg: "variável “lealdade_jin” usada mas não criada", scene: "the_burn", line: 88 },
      { level: "warning", msg: "loop potencial: *goto esperar sem alterar estado", scene: "intro_grid", node: "n15", line: 201 },
      { level: "info", msg: "nó “tensao” não termina em *finish, *goto ou *ending", scene: "intro_grid", node: "n15" },
      { level: "info", msg: "indentação: 2 espaços (consistente em 7 cenas)", scene: null },
    ],
  },
  en: {
    title: "Ghost_Signal",
    author: "K. Ribeiro",
    sceneTitle: "intro_grid",
    sceneSubtitle: "Scene 1 of 7 · 2,847 words",
    scenes: [
      { id: "startup", name: "startup", words: 412, nodes: 6, isStart: true },
      { id: "intro_grid", name: "intro_grid", words: 2847, nodes: 18, current: true },
      { id: "midnight_market", name: "midnight_market", words: 3104, nodes: 24 },
      { id: "ice_breaker", name: "ice_breaker", words: 1980, nodes: 14 },
      { id: "the_burn", name: "the_burn", words: 4221, nodes: 31, warning: true },
      { id: "rooftop", name: "rooftop", words: 1644, nodes: 11 },
      { id: "endings", name: "endings", words: 892, nodes: 8 },
      { id: "stats", name: "choicescript_stats", words: 220, nodes: 3, special: true },
    ],
    variables: [
      { name: "runner_name", type: "string", initial: '""', desc: "Protagonist's handle", uses: 47 },
      { name: "nerve", type: "number", initial: "50", desc: "Cool under pressure (0–100)", uses: 23, fairmath: true },
      { name: "code", type: "number", initial: "30", desc: "Technical skill", uses: 31, fairmath: true },
      { name: "street", type: "number", initial: "40", desc: "Street instinct", uses: 19, fairmath: true },
      { name: "credits", type: "number", initial: "1200", desc: "Cold-wallet balance", uses: 28 },
      { name: "has_deck", type: "boolean", initial: "true", desc: "Owns Uncle Sá's old cyberdeck", uses: 12 },
      { name: "kana_loyalty", type: "number", initial: "0", desc: "Kana's trust (-100 to 100)", uses: 16 },
      { name: "saw_body", type: "boolean", initial: "false", desc: "Found the body in the alley", uses: 8 },
    ],
    achievements: [
      { id: "first_hack", title: "First Hack", points: 5, desc: "Cracked a cheap shop's ICE.", hidden: false },
      { id: "ghost_protocol", title: "Ghost Protocol", points: 25, desc: "Finished the scene with no digital trace.", hidden: false },
      { id: "lone_wolf", title: "Lone Wolf", points: 40, desc: "Refused every offer of help.", hidden: true },
      { id: "kana_romance", title: "Under the Neon Rain", points: 15, desc: "Romance with Kana unlocked.", hidden: true },
    ],
    nodes: [
      {
        id: "n1", type: "passage", x: 60, y: 60, w: 320,
        title: "opening",
        body: "Acid rain has been falling for three days. You're on the roof of Block 7, Tokyo-South Sector, with Uncle Sá's old cyberdeck heavy in your pack. Below, neon holo-ads crawling through the puddles.",
        sets: [{ var: "nerve", op: "=", val: "50" }],
      },
      {
        id: "n2", type: "set", x: 430, y: 60, w: 240,
        title: "*set initial",
        sets: [
          { var: "nerve", op: "=", val: "50" },
          { var: "code", op: "=", val: "30" },
          { var: "street", op: "=", val: "40" },
        ],
      },
      {
        id: "n3", type: "choice", x: 60, y: 320, w: 360,
        title: "first_decision",
        prompt: "What do you do?",
        options: [
          { text: "Take the fire escape down.", to: "n5", cond: null },
          { text: "Jump to the next rooftop.", to: "n6", cond: { type: "if", expr: "nerve >= 40" } },
          { text: "Jack the deck into the antenna now.", to: "n7", cond: { type: "selectable_if", expr: "has_deck" } },
          { text: "Wait for the patrol to pass.", to: "n8", cond: null, hideReuse: true },
        ],
      },
      {
        id: "n4", type: "if", x: 720, y: 60, w: 280,
        title: "*if has_deck",
        branches: [
          { kind: "if", expr: "has_deck and code > 25", to: "n9" },
          { kind: "elseif", expr: "has_deck", to: "n10" },
          { kind: "else", to: "n11" },
        ],
      },
      {
        id: "n5", type: "passage", x: 60, y: 620, w: 300,
        title: "fire_escape",
        body: "The metal stairs groan under your weight. On the third floor you hear voices — corp guards, Northern accent. ${runner_name}, you hold your breath.",
        sets: [{ var: "nerve", op: "%-", val: "10" }],
      },
      {
        id: "n6", type: "passage", x: 430, y: 360, w: 300,
        title: "the_jump",
        body: "Five meters of empty air between buildings. You run. The wind tastes of ozone. @{nerve high|medium|low} the jump goes @{nerve clean|shaky|catastrophic}.",
        sets: [
          { var: "nerve", op: "%+", val: "5" },
          { var: "street", op: "%+", val: "8" },
        ],
      },
      {
        id: "n7", type: "passage", x: 770, y: 360, w: 300,
        title: "hot_antenna",
        body: "Uncle Sá's deck warms in your hands. The neural interface flickers amber — you're inside the city grid. Almost too easy.",
        sets: [{ var: "code", op: "%+", val: "12" }],
      },
      {
        id: "n8", type: "label", x: 60, y: 880, w: 200,
        title: "*label wait",
      },
      {
        id: "n9", type: "goto_scene", x: 1060, y: 60, w: 240,
        title: "*goto_scene midnight_market",
        target: "midnight_market",
      },
      {
        id: "n10", type: "gosub", x: 1060, y: 200, w: 240,
        title: "*gosub verify_deck",
      },
      {
        id: "n11", type: "ending", x: 1060, y: 340, w: 240,
        title: "*ending — 'no deck'",
      },
      {
        id: "n12", type: "checkpoint", x: 430, y: 880, w: 240,
        title: "*save_checkpoint pre_market",
      },
      {
        id: "n13", type: "choice", x: 770, y: 660, w: 340,
        title: "kana_meeting",
        prompt: "Kana lifts her hood. Iron eyes.",
        options: [
          { text: "“You're late.”", to: "n14", cond: null },
          { text: "“I missed you.”", to: "n14", cond: { type: "if", expr: "kana_loyalty > 20" } },
          { text: "Draw your gun.", to: "n15", cond: { type: "selectable_if", expr: "street > 50" } },
        ],
      },
      {
        id: "n14", type: "passage", x: 1170, y: 580, w: 300,
        title: "kana_replies",
        body: "She smiles crooked. — Shut up, ${runner_name}. Let's go.",
        sets: [{ var: "kana_loyalty", op: "+", val: "5" }],
      },
      {
        id: "n15", type: "passage", x: 1170, y: 760, w: 300,
        title: "tension",
        body: "The pistol is heavy. Kana doesn't blink.",
        warning: "potential loop: node returns to *label wait without changing state",
      },
    ],
    edges: [
      { from: "n1", to: "n2", kind: "flow" },
      { from: "n2", to: "n4", kind: "flow" },
      { from: "n1", to: "n3", kind: "flow" },
      { from: "n3", to: "n5", kind: "choice", label: "#1" },
      { from: "n3", to: "n6", kind: "choice", label: "#2 *if" },
      { from: "n3", to: "n7", kind: "choice", label: "#3 *selectable_if" },
      { from: "n3", to: "n8", kind: "choice", label: "#4" },
      { from: "n4", to: "n9", kind: "if" },
      { from: "n4", to: "n10", kind: "elseif" },
      { from: "n4", to: "n11", kind: "else" },
      { from: "n6", to: "n12", kind: "flow" },
      { from: "n7", to: "n12", kind: "flow" },
      { from: "n12", to: "n13", kind: "flow" },
      { from: "n13", to: "n14", kind: "choice", label: "#1" },
      { from: "n13", to: "n14", kind: "choice", label: "#2 *if" },
      { from: "n13", to: "n15", kind: "choice", label: "#3 *selectable_if" },
      { from: "n15", to: "n8", kind: "goto", label: "*goto wait" },
    ],
    lints: [
      { level: "error", msg: "label “wait_too_long” referenced but does not exist", scene: "intro_grid", node: "n8", line: 142 },
      { level: "warning", msg: "variable “jin_loyalty” used but never created", scene: "the_burn", line: 88 },
      { level: "warning", msg: "potential loop: *goto wait without state change", scene: "intro_grid", node: "n15", line: 201 },
      { level: "info", msg: "node “tension” does not end in *finish, *goto or *ending", scene: "intro_grid", node: "n15" },
      { level: "info", msg: "indentation: 2 spaces (consistent across 7 scenes)", scene: null },
    ],
  },
};

const I18N = {
  pt: {
    scenes: "Cenas", variables: "Variáveis", achievements: "Conquistas", assets: "Mídia", search: "Buscar…",
    inspector: "Inspetor", code: "Código", visual: "Visual", preview: "Pré-visualizar",
    play: "Jogar", export: "Exportar", save: "Salvar", autosave: "salvo automaticamente",
    addScene: "Nova cena", addVar: "Nova variável", addAch: "Nova conquista",
    minimap: "minimapa", reflow: "Reorganizar", textMode: "Modo texto",
    nodes: "nós", words: "palavras", choices: "escolhas", endings: "finais",
    nodeTypes: {
      passage: "trecho", choice: "escolha", if: "condicional", set: "atribuição",
      label: "rótulo", goto: "salto", goto_scene: "saltar cena", gosub: "subrotina",
      ending: "fim", checkpoint: "checkpoint", image: "imagem",
    },
    inspectorTabs: ["Conteúdo", "Lógica", "Código bruto"],
    leftTabs: ["Cenas", "Variáveis", "Conquistas", "Mídia"],
    used: "usada em", initial: "inicial", desc: "descrição",
    type: "tipo", scene: "cena",
    consoleTitle: "Console",
    errors: "erros", warnings: "alertas",
    sectionStory: "história", sectionBranching: "ramificação", sectionPolish: "polimento",
    bodyLabel: "narrativa", choiceLabel: "escolha exibida ao jogador",
    addOption: "+ adicionar opção", reuseRules: "reúso",
    appliesTo: "aplica em", linterPasses: "linter ✓",
    quickTest: "Teste rápido", randomTest: "Teste aleatório",
    breadcrumb: "intro_grid › primeira_decisão",
    cmdPalette: "⌘K abrir paleta",
    indentRule: "indentação: espaços (2)",
    encoding: "UTF-8",
    fairmath: "fairmath",
    everyOpen: "todos os caminhos abertos",
    storyCraft: "ofício de escrita",
  },
  en: {
    scenes: "Scenes", variables: "Variables", achievements: "Achievements", assets: "Media", search: "Search…",
    inspector: "Inspector", code: "Code", visual: "Visual", preview: "Preview",
    play: "Play", export: "Export", save: "Save", autosave: "autosaved",
    addScene: "New scene", addVar: "New variable", addAch: "New achievement",
    minimap: "minimap", reflow: "Reflow", textMode: "Text mode",
    nodes: "nodes", words: "words", choices: "choices", endings: "endings",
    nodeTypes: {
      passage: "passage", choice: "choice", if: "conditional", set: "set",
      label: "label", goto: "goto", goto_scene: "goto scene", gosub: "subroutine",
      ending: "ending", checkpoint: "checkpoint", image: "image",
    },
    inspectorTabs: ["Content", "Logic", "Raw code"],
    leftTabs: ["Scenes", "Variables", "Achievements", "Media"],
    used: "used in", initial: "initial", desc: "description",
    type: "type", scene: "scene",
    consoleTitle: "Console",
    errors: "errors", warnings: "warnings",
    sectionStory: "story", sectionBranching: "branching", sectionPolish: "polish",
    bodyLabel: "narrative", choiceLabel: "choice shown to player",
    addOption: "+ add option", reuseRules: "reuse",
    appliesTo: "applies to", linterPasses: "linter ✓",
    quickTest: "Quick test", randomTest: "Random test",
    breadcrumb: "intro_grid › first_decision",
    cmdPalette: "⌘K open palette",
    indentRule: "indent: spaces (2)",
    encoding: "UTF-8",
    fairmath: "fairmath",
    everyOpen: "all paths open",
    storyCraft: "story craft",
  },
};

window.STORY = STORY;
window.I18N = I18N;
