// Inspired by the renderer/graph stage in M3ales/choicescript-tree (MIT)
// https://github.com/M3ales/choicescript-tree
// ChoiceForge's version is simpler: it emits the visible scene graph 1:1,
// without CFG inlining, gosub flattening, or SCC. For full static analysis,
// see choicescript-tree's pipeline.

import type { ChoiceForgeProject, SceneGraph, StoryEdge, StoryNode } from "./types";

// Approximated hex palette matching the editor's OKLCH tokens. Graphviz
// doesn't grok oklch() so we ship near-equivalent sRGB hex.
const NODE_COLORS: Record<StoryNode["type"], { stroke: string; fill: string }> = {
  passage:            { stroke: "#3768c1", fill: "#dbe6f7" },
  choice:             { stroke: "#a13fc7", fill: "#ecdaf2" },
  fake_choice:        { stroke: "#a13fc7", fill: "#ecdaf2" },
  if:                 { stroke: "#b58524", fill: "#f4e5c0" },
  set:                { stroke: "#479464", fill: "#d9ecde" },
  label:              { stroke: "#6a6a6a", fill: "#e6e6e6" },
  goto:               { stroke: "#c97a1f", fill: "#f4dabb" },
  goto_scene:         { stroke: "#c97a1f", fill: "#f4dabb" },
  gosub:              { stroke: "#c25238", fill: "#f0d3c8" },
  gosub_scene:        { stroke: "#c25238", fill: "#f0d3c8" },
  return:             { stroke: "#c25238", fill: "#f0d3c8" },
  ending:             { stroke: "#3d3d3d", fill: "#d9d9d9" },
  finish:             { stroke: "#3d3d3d", fill: "#d9d9d9" },
  checkpoint:         { stroke: "#2f8aa8", fill: "#d3e7ee" },
  restore_checkpoint: { stroke: "#2f8aa8", fill: "#d3e7ee" },
  page_break:         { stroke: "#2f8aa8", fill: "#d3e7ee" },
  comment:            { stroke: "#888888", fill: "#f1f1f1" },
  input_text:         { stroke: "#479464", fill: "#d9ecde" },
  input_number:       { stroke: "#479464", fill: "#d9ecde" },
  rand:               { stroke: "#479464", fill: "#d9ecde" },
  temp:               { stroke: "#479464", fill: "#d9ecde" },
  params:             { stroke: "#479464", fill: "#d9ecde" },
  image:              { stroke: "#3768c1", fill: "#dbe6f7" },
  sound:              { stroke: "#3768c1", fill: "#dbe6f7" },
  achieve:            { stroke: "#bf882d", fill: "#f5e2bf" },
};

const EDGE_STYLE: Record<StoryEdge["kind"], string> = {
  flow: "solid",
  choice: "solid",
  goto: "dashed",
  if: "solid",
  elseif: "solid",
  else: "solid",
};

const MAX_LABEL_BODY_CHARS = 60;

export interface ExportDotOptions {
  /** If set, only this scene is exported (no cluster). If absent, every non-special scene becomes a cluster. */
  sceneName?: string;
}

export function exportProjectAsDot(project: ChoiceForgeProject, options: ExportDotOptions = {}): string {
  const lines: string[] = [];
  lines.push(`digraph "${escapeDot(project.title || "ChoiceForge project")}" {`);
  lines.push("  // Generated by ChoiceForge — github.com/viniman27/ChoiceForge");
  lines.push("  rankdir=LR;");
  lines.push(`  graph [fontname="Helvetica", fontsize=10, splines=spline, label=${quoteDot(`${project.title || "Untitled"} — by ${project.author || "Unknown"}`)}, labelloc="t"];`);
  lines.push(`  node  [fontname="Helvetica", fontsize=10, shape=box, style="filled,rounded", penwidth=1.4];`);
  lines.push(`  edge  [fontname="Helvetica", fontsize=9, color="#666666"];`);
  lines.push("");

  if (options.sceneName) {
    const graph = pickSceneGraph(project, options.sceneName);
    if (!graph) {
      lines.push(`  // scene "${escapeDot(options.sceneName)}" not found`);
    } else {
      emitGraph(lines, options.sceneName, graph, /*asCluster*/ false);
    }
  } else {
    const sceneGraphs = listExportableScenes(project);
    sceneGraphs.forEach(({ sceneName, graph }) => {
      emitGraph(lines, sceneName, graph, /*asCluster*/ true);
      lines.push("");
    });
    emitCrossSceneEdges(lines, project);
  }

  lines.push("}");
  return lines.join("\n") + "\n";
}

function listExportableScenes(project: ChoiceForgeProject): Array<{ sceneName: string; graph: SceneGraph }> {
  const out: Array<{ sceneName: string; graph: SceneGraph }> = [];
  for (const scene of project.scenes) {
    if (scene.special) continue;
    const graph = pickSceneGraph(project, scene.name);
    if (graph && graph.nodes.length > 0) out.push({ sceneName: scene.name, graph });
  }
  return out;
}

function pickSceneGraph(project: ChoiceForgeProject, sceneName: string): SceneGraph | null {
  if (project.sceneData && project.sceneData[sceneName]) return project.sceneData[sceneName];
  if (sceneName === project.sceneTitle) return { nodes: project.nodes, edges: project.edges };
  return null;
}

function emitGraph(lines: string[], sceneName: string, graph: SceneGraph, asCluster: boolean) {
  const indent = asCluster ? "    " : "  ";
  if (asCluster) {
    lines.push(`  subgraph "cluster_${escapeDot(sceneName)}" {`);
    lines.push(`    label="${escapeDot(sceneName)}";`);
    lines.push(`    style="rounded,dashed"; color="#999999"; fontcolor="#333333";`);
  }
  graph.nodes.forEach((node) => {
    const color = NODE_COLORS[node.type];
    const fill = color?.fill ?? "#f5f5f5";
    const stroke = color?.stroke ?? "#444444";
    const label = composeNodeLabel(node);
    lines.push(`${indent}"${nodeKey(sceneName, node.id)}" [label=${quoteDot(label)}, color="${stroke}", fillcolor="${fill}"];`);
  });
  graph.edges.forEach((edge) => {
    const style = EDGE_STYLE[edge.kind] ?? "solid";
    const attrs = [`style=${style}`];
    if (edge.label) attrs.push(`label=${quoteDot(edge.label)}`);
    lines.push(`${indent}"${nodeKey(sceneName, edge.from)}" -> "${nodeKey(sceneName, edge.to)}" [${attrs.join(", ")}];`);
  });
  if (asCluster) lines.push("  }");
}

function emitCrossSceneEdges(lines: string[], project: ChoiceForgeProject) {
  let emittedHeader = false;
  for (const scene of project.scenes) {
    if (scene.special) continue;
    const graph = pickSceneGraph(project, scene.name);
    if (!graph) continue;
    for (const node of graph.nodes) {
      const target = node.target;
      if (!target) continue;
      // *goto_scene / *gosub_scene target field is the destination scene name.
      if (node.type !== "goto_scene" && node.type !== "gosub_scene") continue;
      const targetGraph = pickSceneGraph(project, target);
      if (!targetGraph || targetGraph.nodes.length === 0) continue;
      const firstNodeId = targetGraph.nodes[0].id;
      if (!emittedHeader) {
        lines.push("  // cross-scene edges (*goto_scene / *gosub_scene)");
        emittedHeader = true;
      }
      const style = node.type === "gosub_scene" ? "dotted" : "dashed";
      lines.push(`  "${nodeKey(scene.name, node.id)}" -> "${nodeKey(target, firstNodeId)}" [style=${style}, color="#3768c1", lhead="cluster_${escapeDot(target)}", label="→ ${escapeDot(target)}"];`);
    }
  }
}

function composeNodeLabel(node: StoryNode): string {
  const headerPrefix = NODE_COLORS[node.type] ? `[${node.type}]` : `[${node.type}]`;
  const headerName = node.title?.trim() || node.id;
  const header = `${headerPrefix} ${headerName}`;
  const bodySnippet = (node.body ?? node.prompt ?? "").trim().replace(/\s+/g, " ");
  if (!bodySnippet) return header;
  const truncated = bodySnippet.length > MAX_LABEL_BODY_CHARS
    ? bodySnippet.slice(0, MAX_LABEL_BODY_CHARS - 1) + "…"
    : bodySnippet;
  return `${header}\n${truncated}`;
}

function nodeKey(sceneName: string, nodeId: string): string {
  return `${sceneName}__${nodeId}`;
}

/** Escape special chars used inside an unquoted DOT identifier (for labels and IDs). */
function escapeDot(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/** Wrap a value as a DOT-quoted string, handling embedded newlines (`\n` → DOT `\n`). */
function quoteDot(s: string): string {
  // DOT supports `\n` inside double-quoted strings for newlines. Backslashes
  // and quotes both need escaping.
  const escaped = s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n");
  return `"${escaped}"`;
}
